init-scripts: ensure processes are not started twice
Usually, start-stop-daemon makes sure that the same process
is not started twice. However, with the bash scripts that we start,
the mechanism does not function. We can start the same process
with the same start-stop-daemon command twice.
In order to prevent this behavior, we add an additional command
that checks for a living process with the given PID before
starting a new instance.

diff --git a/init-scripts/libipho b/init-scripts/libipho
--- a/init-scripts/libipho
+++ b/init-scripts/libipho
@@ -27,6 +27,17 @@ STOPOPTS="--stop --pidfile=$PIDFILE"
 
 case "$1" in
   start)
+    # start-stop-daemon fails to recognize an already running instance
+    # of the process and therefore does not prevent us from starting
+    # the process twice. Therefore, we explicitly check for the
+    # existence of a process with the given PID and abort if
+    # a corresponding process has been found.
+    start-stop-daemon -p $PIDFILE -t -K 2>&1 > /dev/null
+    ISDEAD=$?
+    if [ "$ISDEAD" = "0" ]; then
+      echo "A process the the PID specified in $PIDFILE is already running."
+      exit 0
+    fi
     echo -n "Starting $DESC: "
     start-stop-daemon $STARTOPTS -x "$DAEMON"
     echo "$NAME."
